version: '3.9'

services:

    db:
        image: postgres:17.2
        restart: unless-stopped
        container_name: daily-reflect-postgres
        volumes:
            - daily-reflect-postgres-data:/var/lib/postgresql
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}


    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "8080:8080"

    maildev:
        image: maildev/maildev
        restart: unless-stopped
        ports:
            - "1080:1080"
            - "1025:1025"
        profiles: [dev]


volumes:
    daily-reflect-postgres-data:
