CREATE SEQUENCE IF NOT EXISTS journals_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE journal_tags
(
    journal_id BIGINT NOT NULL,
    tags       VARCHAR(255)
);

CREATE TABLE journals
(
    id                 BIGINT NOT NULL,
    date               date   NOT NULL,
    content            VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_journals PRIMARY KEY (id)
);

CREATE TABLE password_reset_tokens
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token              VARCHAR(255)                            NOT NULL,
    expiration_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_email         VARCHAR                                 NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (id)
);

CREATE TABLE profile_journals
(
    journal_id BIGINT,
    profile_id BIGINT NOT NULL,
    CONSTRAINT pk_profile_journals PRIMARY KEY (profile_id)
);

CREATE TABLE profiles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_profiles PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username           VARCHAR(30)                             NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    password           VARCHAR(255)                            NOT NULL,
    is_enabled         BOOLEAN                                 NOT NULL,
    email_verified_at  TIMESTAMP WITHOUT TIME ZONE,
    verification_code  VARCHAR(255),
    code_expiration    TIMESTAMP WITHOUT TIME ZONE,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_user_email UNIQUE (user_email);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT FK_PASSWORD_RESET_TOKENS_ON_USER_EMAIL FOREIGN KEY (user_email) REFERENCES users (email);

ALTER TABLE profiles
    ADD CONSTRAINT FK_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE journal_tags
    ADD CONSTRAINT fk_journal_tags_on_journal FOREIGN KEY (journal_id) REFERENCES journals (id);

ALTER TABLE profile_journals
    ADD CONSTRAINT fk_projou_on_journal FOREIGN KEY (profile_id) REFERENCES journals (id);

ALTER TABLE profile_journals
    ADD CONSTRAINT fk_projou_on_profile FOREIGN KEY (journal_id) REFERENCES profiles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);