ALTER TABLE users
ADD COLUMN encrypted_dek VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN iv VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN salt VARCHAR(255) NOT NULL DEFAULT '';